# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Run and Test

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build test
      run: mvn test
    - name: Build and Generate coverage
      run: mvn test jacoco:report
    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./target/site/jacoco
        retention-days: 1
        
    - name: Build C++
      run: g++ -Wall -Wextra -o sender -fprofile-arcs -ftest-coverage -o testchecker Sender/*.c*
      
    - name: Build main
      run:  mvn -B package --file pom.xml -Dmaven.test.skip=true
      
    - name: Piping
      run: sender | java -jar target/workflow-github-actions-1.0-SNAPSHOT.jar
